var annotated_dup =
[
    [ "ADSRComponent", "classADSRComponent.html", "classADSRComponent" ],
    [ "AppController", "classAppController.html", "classAppController" ],
    [ "AppLookAndFeel", "classAppLookAndFeel.html", "classAppLookAndFeel" ],
    [ "AuthResult", "structAuthResult.html", "structAuthResult" ],
    [ "BackendAiManager", "classBackendAiManager.html", "classBackendAiManager" ],
    [ "BackendAuthManager", "classBackendAuthManager.html", "classBackendAuthManager" ],
    [ "BackendManager", "classBackendManager.html", "classBackendManager" ],
    [ "BackendProfileManager", "classBackendProfileManager.html", "classBackendProfileManager" ],
    [ "BottomBarComponent", "classBottomBarComponent.html", "classBottomBarComponent" ],
    [ "DataModel", "classDataModel.html", "classDataModel" ],
    [ "FilterComponent", "classFilterComponent.html", "classFilterComponent" ],
    [ "FrequencySlider", "classFrequencySlider.html", "classFrequencySlider" ],
    [ "FrequencyVolumeComponent", "classFrequencyVolumeComponent.html", "classFrequencyVolumeComponent" ],
    [ "GenerateButton", "classGenerateButton.html", "classGenerateButton" ],
    [ "HarmoniaAudioProcessor", "classHarmoniaAudioProcessor.html", "classHarmoniaAudioProcessor" ],
    [ "HarmoniaAudioProcessorEditor", "classHarmoniaAudioProcessorEditor.html", "classHarmoniaAudioProcessorEditor" ],
    [ "HarmoniaSound", "classHarmoniaSound.html", "classHarmoniaSound" ],
    [ "HarmoniaVoice", "classHarmoniaVoice.html", "classHarmoniaVoice" ],
    [ "LoginPage", "classLoginPage.html", "classLoginPage" ],
    [ "MainComponent", "classMainComponent.html", "classMainComponent" ],
    [ "OscilloscopeComponent", "classOscilloscopeComponent.html", "classOscilloscopeComponent" ],
    [ "PatchCallResult", "structPatchCallResult.html", "structPatchCallResult" ],
    [ "PatchParams", "structPatchParams.html", "structPatchParams" ],
    [ "ProfileResult", "structProfileResult.html", "structProfileResult" ],
    [ "SignupPage", "classSignupPage.html", "classSignupPage" ],
    [ "SynthComponent", "classSynthComponent.html", "classSynthComponent" ],
    [ "ThemeAndLayoutConverter", "classThemeAndLayoutConverter.html", "classThemeAndLayoutConverter" ],
    [ "ThemePalette", "structThemePalette.html", "structThemePalette" ],
    [ "TitleComponent", "classTitleComponent.html", "classTitleComponent" ],
    [ "TopBarComponent", "classTopBarComponent.html", "classTopBarComponent" ],
    [ "UserProfile", "structUserProfile.html", "structUserProfile" ],
    [ "UserSession", "structUserSession.html", "structUserSession" ],
    [ "VolumeSlider", "classVolumeSlider.html", "classVolumeSlider" ],
    [ "WaveformSelector", "classWaveformSelector.html", "classWaveformSelector" ],
    [ "WelcomePage", "classWelcomePage.html", "classWelcomePage" ]
];