var dir_1fc41604e760a4389ddc5e5aa71c9c0b =
[
    [ "ADSRComponent.cpp", "ADSRComponent_8cpp.html", null ],
    [ "ADSRComponent.h", "ADSRComponent_8h.html", "ADSRComponent_8h" ],
    [ "BottomBarComponent.cpp", "BottomBarComponent_8cpp.html", null ],
    [ "BottomBarComponent.h", "BottomBarComponent_8h.html", "BottomBarComponent_8h" ],
    [ "ComponentsIncludes.h", "ComponentsIncludes_8h.html", null ],
    [ "FilterComponent.cpp", "FilterComponent_8cpp.html", null ],
    [ "FilterComponent.h", "FilterComponent_8h.html", "FilterComponent_8h" ],
    [ "FrequencySlider.h", "FrequencySlider_8h.html", "FrequencySlider_8h" ],
    [ "FrequencyVolumeComponent.cpp", "FrequencyVolumeComponent_8cpp.html", null ],
    [ "FrequencyVolumeComponent.h", "FrequencyVolumeComponent_8h.html", "FrequencyVolumeComponent_8h" ],
    [ "GenerateButton.h", "GenerateButton_8h.html", "GenerateButton_8h" ],
    [ "OscilloscopeComponent.cpp", "OscilloscopeComponent_8cpp.html", null ],
    [ "OscilloscopeComponent.h", "OscilloscopeComponent_8h.html", "OscilloscopeComponent_8h" ],
    [ "Synth.cpp", "Synth_8cpp.html", null ],
    [ "Synth.h", "Synth_8h.html", "Synth_8h" ],
    [ "SynthComponent.cpp", "SynthComponent_8cpp.html", null ],
    [ "SynthComponent.h", "SynthComponent_8h.html", "SynthComponent_8h" ],
    [ "TitleComponent.cpp", "TitleComponent_8cpp.html", null ],
    [ "TitleComponent.h", "TitleComponent_8h.html", "TitleComponent_8h" ],
    [ "TopBarComponent.cpp", "TopBarComponent_8cpp.html", null ],
    [ "TopBarComponent.h", "TopBarComponent_8h.html", "TopBarComponent_8h" ],
    [ "VolumeSlider.h", "VolumeSlider_8h.html", "VolumeSlider_8h" ],
    [ "WaveformSelector.h", "WaveformSelector_8h.html", "WaveformSelector_8h" ]
];