name: Harmonia CI/CD

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64

      - name: Build
        run: cmake --build build --config Release

      - name: Check EXE
        run: |
          if (!(Test-Path "build/HarmoniaPlugin_artefacts/Release/Standalone/HarmoniaPlugin.exe")) {
            Write-Error "EXE not found"
            exit 1
          }

      - name: Check VST3
        run: |
          if (!(Test-Path "build/HarmoniaPlugin_artefacts/Release/VST3/HarmoniaPlugin.vst3")) {
            Write-Error "VST3 not found"
            exit 1
          }

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Harmonia-EXE
          path: build/HarmoniaPlugin_artefacts/Release/Standalone/HarmoniaPlugin.exe

      - name: Create Release Folder
        if: github.ref == 'refs/heads/main'
        run: mkdir release

      - name: Zip VST3
        if: github.ref == 'refs/heads/main'
        run: |
          Compress-Archive `
            -Path "build/HarmoniaPlugin_artefacts/Release/VST3/HarmoniaPlugin.vst3" `
            -DestinationPath "release/Harmonia.zip"

      - name: Upload ZIP Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: Harmonia-Release
          path: release/Harmonia.zip

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download ZIP Artifact
        uses: actions/download-artifact@v4
        with:
          name: Harmonia-Release
          path: release

      - name: Upload ZIP to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "release/Harmonia.zip"
          target: "/var/www/harmonia-downloads/release"