name: Harmonia check compile and release vps

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64

      - name: Build
        run: cmake --build build --config Release

      - name: Check EXE
        run: |
          if (!(Test-Path "build/HarmoniaPlugin_artefacts/Release/Standalone/HarmoniaPlugin.exe")) {
            Write-Error "EXE not found"
            exit 1
          }

      - name: Check VST3
        run: |
          if (!(Test-Path "build/HarmoniaPlugin_artefacts/Release/VST3/HarmoniaPlugin.vst3")) {
            Write-Error "VST3 not found"
            exit 1
          }

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Harmonia-EXE
          path: build/HarmoniaPlugin_artefacts/Release/Standalone/HarmoniaPlugin.exe

      - name: Create Release Folder
        if: github.ref == 'refs/heads/main'
        run: mkdir release

      - name: Zip VST3
        if: github.ref == 'refs/heads/main'
        run: |
          Compress-Archive `
            -Path "build/HarmoniaPlugin_artefacts/Release/VST3/HarmoniaPlugin.vst3" `
            -DestinationPath "release/Harmonia.zip"

      - name: Upload ZIP Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: Harmonia-Release
          path: release/Harmonia.zip

  - name: Zip VST3
  if: github.ref == 'refs/heads/main'
  shell: powershell
  run: |
    New-Item -ItemType Directory -Force -Path release

    Copy-Item `
      -Path "build/HarmoniaPlugin_artefacts/Release/VST3/HarmoniaPlugin.vst3" `
      -Destination "release/HarmoniaPlugin.vst3" `
      -Recurse

    Compress-Archive `
      -Path "release/HarmoniaPlugin.vst3" `
      -DestinationPath "release/Harmonia.zip" `
      -Force