name: Push to branch on another repo

on:
  push:
    branches:
      - main

  pull_request:
    types: [closed]
    branches:
      - main

env:
  TARGET_REPO_SSH: "git@github.com:EpitechPromo2027/G-EIP-600-LYN-6-1-eip-swan.sallet.git"
  TARGET_BRANCH: "harmonia-app"

jobs:
  push_to_target:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo (with submodules)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup SSH
        run: |
          set -e
          mkdir -p ~/.ssh
          echo "${{ secrets.SECRET_KEY_PUSH_MIRROR }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          ssh -T git@github.com || true

      - name: Clone target repo branch
        run: |
          set -e
          git clone --single-branch --branch ${{ env.TARGET_BRANCH }} ${{ env.TARGET_REPO_SSH }} .
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Copy source files to target branch
        run: |
          set -e
          rm -rf * .[^.]* || true  # supprime tous les fichiers et dossiers sauf .git
          cp -r ../* . || true     # copie les fichiers du repo source vers le dossier courant (la branche clonée)
          cp -r ../.??* . || true  # copie aussi les fichiers cachés (.gitignore, etc.)
          rm -rf target-repo .github || true  # nettoyage des dossiers inutiles si jamais ils se sont copiés

      - name: Commit and push
        run: |
          set -e
          git add .
          git commit -m "Sync from source repo (main)" || echo "Nothing to commit"
          git push origin ${{ env.TARGET_BRANCH }}
